#!/bin/env zsh
# this shebang isn't strictly necessary but helps neovim recognize this file as
# a zsh script rather than a conf file since it uses a non-standard name.

# Platform Specific ZSH Configuration File

# Create alias for clearing dns cache
alias dnsflush="sudo resolvectl flush-caches"

