[general]
import = [
    "~/.config/alacritty/tokyo-night.toml"
]

[window]
# Default to 110x28
dimensions = {
    columns = 110,
    lines = 28
}

[font]
size = 13.5
normal = {
    family = "SFMono Nerd Font"
}
