context.modules = [
  # Stream Audio Input ← XR18 Out 3/4
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Stream Audio Input (XR18 Out 3/4)"
      capture.props = {
        node.name      = "remap_stream_in_capture"
        audio.channels = 2
        audio.position = [ RL RR ]
        target.object  = "alsa_input.usb-BEHRINGER_X18_XR18_32065F4B-00.multichannel-input"
        stream.dont-remix = true
        node.passive   = true
      }
      playback.props = {
        node.name      = "remap_stream_in"
        media.class    = "Audio/Source"
        audio.channels = 2
        audio.position = [ FL FR ]
      }
    }
  }

  # Microphone Input ← XR18 Out 6 (mono, from LFE/ch6)
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "Microphone Audio Input (XR18 Out 6)"
      capture.props = {
        node.name      = "remap_mic_in_capture"
        audio.channels = 1
        audio.position = [ LFE ]
        target.object  = "alsa_input.usb-BEHRINGER_X18_XR18_32065F4B-00.multichannel-input"
        stream.dont-remix = true
        node.passive   = true
      }
      playback.props = {
        node.name      = "remap_mic_in"
        media.class    = "Audio/Source"
        audio.channels = 1
        audio.position = [ MONO ]
      }
    }
  }
]
