#!/bin/env zsh
# this shebang isn't strictly necessary but helps neovim recognize this file as
# a zsh script rather than a conf file since it uses a non-standard name.

# Mac OS Platform Specific zsh configuration

# initialize completions with ZSH's compinit.
# ALL COMPLETIONS MUST BE LOADED BEFORE THIS LINE
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
        compinit
    else
        compinit -C
    fi
fi

