#!/bin/env zsh
# this shebang isn't strictly necessary but helps neovim recognize this file as
# a zsh script rather than a conf file since it uses a non-standard name.

. "$HOME/.asdf/asdf.sh"

# append completions to fpath
FPATH="${ASDF_DIR}/completions:$FPATH"

# initialize completions with ZSH's compinit.
# ALL COMPLETIONS MUST BE LOADED BEFORE THIS LINE
# autoload -Uz compinit
#
# for dump in ~/.zcompdump(N.mh+24); do
#     compinit
# done
#
# compinit -C

