#!/bin/env zsh
# this shebang isn't strictly necessary but helps neovim recognize this file as
# a zsh script rather than a conf file since it uses a non-standard name.

[ -z "$ZPROF" ] || zmodload zsh/zprof

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# use powerlevel10k if installed
[ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ] && ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=()

# Uncomment the following line to disable the async git prompt
zstyle ':omz:alpha:lib:git' async-prompt no

source $ZSH/oh-my-zsh.sh

# User configuration

# call this from a zle widget if it changes any info shown in the p10k prompt
# (e.g. git HEAD)
redraw_p10k_prompt() {
    [[ "${ZSH_THEME}" == "powerlevel10k/powerlevel10k" ]] || return

    local f
    for f in chpwd "${chpwd_functions[@]}" precmd "${precmd_functions[@]}"; do
        [[ "${+functions[$f]}" == 0 ]] || "$f" &>/dev/null || true
    done
    p10k display -r
}

# Tell zsh to deduplicate $PATH entries. This helps ensure that calls to the
# 'reload' command don't screw up your path (since exec doesn't clear the env
# but all of your `PATH=/idk/bin:$PATH` lines are called again)
typeset -aU path

# Load system-specific zsh configuration.
# This is where you put anything that doesn't apply to all systems, such as path
# entries for software that you don't use on every machine.
source ~/.zsh_system

# Load platform-specific zsh configuration if present.
# This file should be automatically linked by the dotfiles installer.
# (This is deprecated and I want to get rid of it soon)
if [ -f ~/.zsh_dist ]; then
    source ~/.zsh_dist
fi

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Load all of our user-specific things like aliases and keybinds from this file
source ~/.zsh_profile

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Run zprof if the environment variable is set
[ -z "$ZPROF" ] || zprof
